#!/bin/bash

set -x
if [ -z "$USER" ]
then
    echo 'Please provide a ssh username using the environment variable "USER"'
    exit 1
fi
if [ -n "$HOST" ]
then
    HOST="HOST=$HOST"
fi
docker-compose run --rm recipes /bin/bash -c "USER=$USER $HOST ./script/fetch-html --with-resources $1" || exit 1
